name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build and bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toAppImage . -o Sims4-mod-manager-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: Sims4-mod-manager-linux

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-binary

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Sims4-mod-manager-linux
          generate_release_notes: true
